services:
  servidor:
    build: 
      context: ./reqrep
      dockerfile: Dockerfile_servidor
    ports:
      - "5555:5555"
    networks:
      - chat_network
    volumes:
      - ./reqrep/data:/app/data

  proxy:
    build: ./proxy
    ports:
      - "5557:5557"
      - "5558:5558"
    networks:
      - chat_network

  cliente:
    build:
      context: ./reqrep
      dockerfile: Dockerfile_cliente
    command: python cliente.py
    networks:
      - chat_network
    depends_on:
      - servidor
      - proxy
    tty: true
    stdin_open: true

networks:
  chat_network:
    driver: bridge