FROM node:20

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    libzmq3-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

COPY referencia.js .

EXPOSE 6000

CMD ["node", "referencia.js"]