# bots/Dockerfile_bot
FROM python:3.9-slim

WORKDIR /app

# Instala dependências Python
RUN pip install --no-cache-dir \
    pyzmq \
    msgpack

# Copia o script do bot
COPY bot.py .

# Comando para iniciar o bot
CMD ["python", "bot.py"]