FROM debian:stable-slim

WORKDIR /app

RUN apt update && apt install -y \
    gcc \
    make \
    cmake \
    pkg-config \
    libzmq3-dev \
    libmsgpack-dev \
    libc-dev \
    build-essential \
    && apt clean

COPY cliente.c .
COPY cliente.h .

RUN gcc -o cliente cliente.c -lzmq -lmsgpack-c -lpthread

CMD ["./cliente"]
