FROM gcc:latest

WORKDIR /app

# Instala as dependências necessárias
RUN apt-get update && apt-get install -y \
    libzmq3-dev \
    libmsgpack-c-dev \
    pkg-config \
    cmake \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia os arquivos do cliente para dentro do container
COPY . .

# Compila o cliente com as bibliotecas corretas
RUN gcc -o cliente cliente.c -lzmq -lmsgpack-c -lpthread


# Apenas debug: mostra as portas que o cliente usa
ENV SERVER_PORT=5555
ENV PROXY_XSUB_PORT=5565
ENV PROXY_XPUB_PORT=5568

CMD echo "🚀 Iniciando cliente..." && \
    echo "🔌 SERVER_PORT=$SERVER_PORT | XSUB=$PROXY_XSUB_PORT | XPUB=$PROXY_XPUB_PORT" && \
    ./cliente
